version: '3.7'
services:
    db:
        image: postgres:10.5
        restart: always
        environment: 
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=postgres     
          - POSTGRES_DB=challenge   
        ports:
          - '5432:5432'
        volumes:
          - ./sql:/docker-entrypoint-initdb.d/          

    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.10.0
        container_name: elasticsearch
        environment:
          - xpack.security.enabled=false
          - discovery.type=single-node
          - discovery.seed_hosts=elasticsearch
        ulimits:
          memlock:
            soft: -1
            hard: -1
          nofile:
            soft: 65536
            hard: 65536
        cap_add:
          - IPC_LOCK
        volumes:
          - ./data/elasticsearch-data:/usr/share/elasticsearch/data
        ports:
          - 9200:9200
          - 9300:9300

    springchallenge:        
        build: ./springchallenge
        depends_on:  
          - db
          - elasticsearch
        restart: on-failure
        ports:  
          - 8080:8080
        environment:
          - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/challenge
          - SPRING_DATASOURCE_USERNAME=postgres
          - SPRING_DATASOURCE_PASSWORD=postgres
          - SPRING_JPA_HIBERNATE_DDL_AUTO=none
        